
if(NOT PREPROCESSOR_INCLUDE_DIR_1)
    message(SEND_ERROR "PREPROCESSOR_INCLUDE_DIR_1 not set.")
    set(bad_input true)
endif()
if(NOT PREPROCESSOR_INCLUDE_DIR_2)
    message(SEND_ERROR "PREPROCESSOR_INCLUDE_DIR_2 not set.")
    set(bad_input true)
endif()
if(NOT IN_FILE)
    message(SEND_ERROR "IN_FILE not set.")
    set(bad_input true)
endif()
if(NOT OUT_FILE)
    message(SEND_ERROR "OUT_FILE not set.")
    set(bad_input true)
endif()
if(NOT CMAKE_C_COMPILER)
    message(SEND_ERROR "CMAKE_C_COMPILER not set")
    set(bad_input true)
endif()
if(NOT CMAKE_C_COMPILER_ID)
    message(SEND_ERROR "CMAKE_C_COMPILER_ID not set")
    set(bad_input true)
endif()
if(bad_input)
    message(FATAL_ERROR "One or more required input variables are not set")
endif()

cmake_policy(PUSH)
cmake_policy(SET CMP0007 NEW)

include("${CsoundCMake.Core_DIR}/Source/functions/preprocess_file.cmake")
preprocess_file("${IN_FILE}" "${OUT_FILE}")

cmake_policy(POP)
