
#ifndef CsoundCMake_csound_definitions_h
#define CsoundCMake_csound_definitions_h

#define GUARD_POINT_SIZE 1

#define LFO_SHAPE_SINE 0 // default
#define LFO_SHAPE_TRIANGLE 1
#define LFO_SHAPE_SQUARE_BIPOLAR 2
#define LFO_SHAPE_SQUARE_UNIPOLAR 3
#define LFO_SHAPE_SAWTOOTH 4
#define LFO_SHAPE_SAWTOOTH_DOWN 5

#define TABLEI_IXOFF_DEFAULT 0
#define TABLEI_IWRAP_NOWRAP 0
#define TABLEI_IWRAP_WRAPAROUND 1

#define VCO2_WAVEFORM_TRIANGLE_NO_RAMP 12
#define VCO2_WAVEFORM_SQUARE_NO_PWM 10
#define VCO2_WAVEFORM_INTEGRATED_SAWTOOTH 8
#define VCO2_WAVEFORM_PULSE_NOT_NORMALIZED 6
#define VCO2_WAVEFORM_SAWTOOTH_TRIANGLE_RAMP 4
#define VCO2_WAVEFORM_SQUARE_PWM 2
#define VCO2_WAVEFORM_SQUARE 0 // default

#endif // include guard
