
include_guard()

set(CSOUND_CMAKE_OUTPUT_DIR "${CMAKE_BINARY_DIR}")
set(CSOUND_CMAKE_BUILD_INLINED_CONFIGURED_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/inlined/configured")

if("${BUILD_PLAYBACK_CSD}" STREQUAL "ON")
    set(CSOUND_CMAKE_PLUGIN_OUTPUT_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/playback")
else()
    set(CSOUND_CMAKE_PLUGIN_OUTPUT_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/output")
endif()

if("${Build_InlineIncludes}" STREQUAL "ON" OR "${BUILD_PLAYBACK_CSD}" STREQUAL "ON")
    set(CSOUND_CMAKE_OUTPUT_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/inlined")
else()
    set(CSOUND_CMAKE_OUTPUT_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/included")
endif()

set(CSOUND_CMAKE_CONFIGURED_FILES_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/configured")
set(CSOUND_CMAKE_PREPROCESSED_FILES_DIR "${CSOUND_CMAKE_OUTPUT_DIR}/preprocessed")
