
set(BuildPlugin_AU_Export OFF CACHE BOOL "")
set(BuildPlugin_AU_LinkCsdFiles OFF CACHE BOOL "")
set(BuildPlugin_VST3_Export OFF CACHE BOOL "")
set(BuildPlugin_VST3_LinkCsdFiles OFF CACHE BOOL "")
set(Build_InlineIncludes OFF CACHE BOOL "")
set(CABBAGE_PATH "/Applications/Cabbage.app")
set(Cabbage_LogCabbageOutput OFF CACHE BOOL "")
set(Cabbage_UiGrid OFF CACHE BOOL "")
set(Cabbage_UiOutlineGroups OFF CACHE BOOL "")
set(CsoundLog_FileNames OFF CACHE BOOL "")
set(CsoundLog_Level0Trace OFF CACHE BOOL "")
set(CsoundLog_Level1Debug OFF CACHE BOOL "")
set(CsoundLog_Level2Info OFF CACHE BOOL "")
set(CsoundLog_Level3Warning OFF CACHE BOOL "")
set(CsoundLog_Level4Error OFF CACHE BOOL "")
set(CsoundLog_Level5Fatal OFF CACHE BOOL "")
set(CsoundLog_ToCsoundOutput OFF CACHE BOOL "")
set(CsoundLog_ToDawService OFF CACHE BOOL "")
set(CsoundMessages_Benchmarks ON CACHE BOOL "")
set(CsoundMessages_DeprecationWarnings ON CACHE BOOL "")
set(CsoundMessages_NoteAmplitudes ON CACHE BOOL "")
set(CsoundMessages_SamplesOutOfRange ON CACHE BOOL "")
set(CsoundMessages_Warnings ON CACHE BOOL "")
