
set(BuildPlugin_AU_Export OFF CACHE BOOL "")
set(BuildPlugin_AU_LinkCsdFiles OFF CACHE BOOL "")
set(BuildPlugin_VST3_Export OFF CACHE BOOL "")
set(BuildPlugin_VST3_LinkCsdFiles OFF CACHE BOOL "")
set(Build_InlineIncludes OFF CACHE BOOL "")
set(CABBAGE_PATH "/Applications/Cabbage.app")
set(Cabbage_LogCabbageOutput OFF CACHE BOOL "")
set(Cabbage_UiGrid ON CACHE BOOL "")
set(Cabbage_UiOutlineGroups ON CACHE BOOL "")
set(CsoundLog_FileNames OFF CACHE BOOL "")
set(CsoundLog_Level0Trace OFF CACHE BOOL "")
set(CsoundLog_Level1Debug OFF CACHE BOOL "")
set(CsoundLog_Level2Info OFF CACHE BOOL "")
set(CsoundLog_Level3Warning OFF CACHE BOOL "")
set(CsoundLog_Level4Error OFF CACHE BOOL "")
set(CsoundLog_Level5Fatal OFF CACHE BOOL "")
set(CsoundLog_ToCsoundOutput OFF CACHE BOOL "")
set(CsoundLog_ToDawService OFF CACHE BOOL "")
set(CsoundMessages_Benchmarks ON CACHE BOOL "")
set(CsoundMessages_DeprecationWarnings ON CACHE BOOL "")
set(CsoundMessages_NoteAmplitudes ON CACHE BOOL "")
set(CsoundMessages_SamplesOutOfRange ON CACHE BOOL "")
set(CsoundMessages_Warnings ON CACHE BOOL "")

# Convenience settings.
set(CsoundLog_All OFF)
set(CsoundMessages_Silence ON)

if(CsoundLog_All)
    set(CsoundLog_FileNames ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level0Trace ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level1Debug ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level2Info ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level3Warning ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level4Error ON CACHE BOOL "" FORCE)
    set(CsoundLog_Level5Fatal ON CACHE BOOL "" FORCE)
    set(CsoundLog_ToCsoundOutput ON CACHE BOOL "" FORCE)
    set(CsoundLog_ToDawService ON CACHE BOOL "" FORCE)
endif()

if(CsoundMessages_Silence)
    set(CsoundMessages_Benchmarks OFF CACHE BOOL "" FORCE)
    set(CsoundMessages_DeprecationWarnings OFF CACHE BOOL "" FORCE)
    set(CsoundMessages_NoteAmplitudes OFF CACHE BOOL "" FORCE)
    set(CsoundMessages_SamplesOutOfRange OFF CACHE BOOL "" FORCE)
    set(CsoundMessages_Warnings OFF CACHE BOOL "" FORCE)
endif()
