
${CSOUND_IFDEF} TriangleBassMonoSynth_VolumeEnvelopeAttackAndDecayTime
${CSOUND_UNDEF} TriangleBassMonoSynth_VolumeEnvelopeAttackAndDecayTime
${CSOUND_ENDIF}
${CSOUND_IFDEF} TriangleBassMonoSynth_NoteNumberPortamentoTime
${CSOUND_UNDEF} TriangleBassMonoSynth_NoteNumberPortamentoTime
${CSOUND_ENDIF}
